[package]
name = "lyri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
dotenv = "0.15.0"
once_cell = "1.17.1"
regex = "1.8.1"
reqwest = { version = "0.11.10", features = ["json"] }
scraper = "0.16.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tokio = { version = "1.28.1", features = ["full"] }
